# 1 Pytorch基础
## 张量

In [2]:
# pytorch本质是一个基于张量的数学计算工具包

import torch

In [3]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2, 3)  # [0,1)

tensor([[0.1438, 0.6321, 0.4686],
        [0.4005, 0.1931, 0.5903]])

In [ ]:
torch.randn(2, 3)  # 每个值都来自标准正态分布 

tensor([[ 0.0779,  1.1354,  1.9551],
        [ 0.6615, -0.9614,  2.2238]])

In [7]:
torch.zeros(2, 3, dtype = torch.long)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.zeros(2, 3, dtype = torch.double)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [9]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array = [[1.0, 3.8, 2.1], [8.6, 4.0, 2.4]]
torch.tensor(array)

tensor([[1.0000, 3.8000, 2.1000],
        [8.6000, 4.0000, 2.4000]])

In [11]:
import numpy as np
array = np.array([[1.0, 3.8, 2.1], [8.6, 4.0, 2.4]])
torch.from_numpy(array)

tensor([[1.0000, 3.8000, 2.1000],
        [8.6000, 4.0000, 2.4000]], dtype=torch.float64)

In [15]:
# 上面的方式创建的张量会存储在内存中，并使用CPU进行计算，如果想要调用GPU计算，需要直接在GPU中创建张量或者将张量送入到GPU中

torch.rand(2, 3).cuda()

AssertionError: Torch not compiled with CUDA enabled

In [13]:
torch.rand(2, 3).to("mps")

tensor([[0.3990, 0.5155, 0.4374],
        [0.1497, 0.4614, 0.5923]], device='mps:0')

In [14]:
torch.rand(2, 3, device = "mps")

tensor([[0.0140, 0.5337, 0.8425],
        [0.4299, 0.9734, 0.9350]], device='mps:0')

## 张量计算

In [ ]:
# 张量的加减乘除是按元素进行计算的
x = torch.tensor([1, 2, 3], dtype = torch.double)
y = torch.tensor([4, 5, 6], dtype = torch.double)

print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([5., 7., 9.], dtype=torch.float64)
tensor([-3., -3., -3.], dtype=torch.float64)
tensor([ 4., 10., 18.], dtype=torch.float64)
tensor([0.2500, 0.4000, 0.5000], dtype=torch.float64)


In [20]:
x.dot(y)

tensor(32., dtype=torch.float64)

In [21]:
x.sin()

tensor([0.8415, 0.9093, 0.1411], dtype=torch.float64)

In [22]:
x.exp()

tensor([ 2.7183,  7.3891, 20.0855], dtype=torch.float64)

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.double)

In [24]:
x.mean()

tensor(3.5000, dtype=torch.float64)

In [25]:
x.mean(dim = 0)

tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64)

In [26]:
x.mean(dim = 1)

tensor([2., 5.], dtype=torch.float64)

In [27]:
x.mean(dim = 1, keepdim = True)

tensor([[2.],
        [5.]], dtype=torch.float64)

In [28]:
x = torch.tensor([[1, 2, 3], [ 4,  5,  6]], dtype=torch.double)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.double)

torch.cat((x, y), dim = 0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)

In [29]:
torch.cat((x, y), dim = 1)

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]], dtype=torch.float64)

In [30]:
# 使用pytorch计算的好处是：高效的执行速度。尤其是张量存储的数据很多时，还可以借助GPU进一步提高计算速度
import timeit # Python 内置模块，用于精确测量小段代码的执行时间

M = torch.rand(1000, 1000)
print(timeit.timeit(lambda: M.mm(M).mm(M), number = 5000)) # 3次矩阵乘法的链式运算，重复执行5000次

13.997477416007314


In [31]:
N = torch.rand(1000, 1000).to("mps")
print(timeit.timeit(lambda: N.mm(N).mm(N), number = 5000)) 

6.108273541991366


## 自动微分

In [32]:
# 使用pytorch计算梯度，执行tensor.backward()，就会自动通过反向传播算法完成
# 注意：为了计算一个函数对某个变量的导数，需要显式设置该变量是可求导的，也就是在张量生成时，设置requires_grad=True
x = torch.tensor([2.], requires_grad = True)
y = torch.tensor([3.], requires_grad = True)

z = (x + y) * (y - 2)
print(z)

tensor([5.], grad_fn=<MulBackward0>)


In [33]:
z.backward()
print(x.grad, y.grad)

tensor([1.]) tensor([6.])


## 调整张量形状

In [34]:
x = torch.tensor([1,2,3,4,5,6])
print(x, x.shape)

tensor([1, 2, 3, 4, 5, 6]) torch.Size([6])


In [ ]:
# 使用view操作的张量必须是连续的，如果非连续，需要先通过contiguous将其变为连续的
# 也可以用reshape，它与view功能几乎一致，但可以自动处理非连续张量
x.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
x.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [37]:
x.view(-1, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [40]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
x.transpose(0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [42]:
# transpose只能交换2个维度，permute能直接设置新的维度排列方式
x = torch.tensor([[[1, 2, 3],[4, 5, 6]]])
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])


In [ ]:
 # 原始张量：（批次，行，列）。现在：提取“列”作为新的主要维度，原始张量有3列（维度2），所以新张量有3层，每层收集原始数据中“同一列的所有行”
x = x.permute(2, 0, 1) 
print(x, x.shape)

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]]) torch.Size([3, 1, 2])


## 广播机制

In [44]:
x = torch.arange(1, 4).view(3, 1)
y = torch.arange(4, 6).view(1, 2)
print(x)
print(y)

tensor([[1],
        [2],
        [3]])
tensor([[4, 5]])


In [ ]:
# 它们形状分别为(3,1)和(1,2)，如果要进行按元素运算，必须将它们都扩展为形状(3,2)的张量。具体地，就是将x的第1列复制到第2列，将y的第1行复制到第2、3 行。实际上，可以直接进行运算，Pytorch 会自动执行广播：
print(x + y)

tensor([[5, 6],
        [6, 7],
        [7, 8]])


## 索引与切片

In [47]:
x = torch.arange(12).view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [48]:
x[1, 3]

tensor(7)

In [49]:
x[1]

tensor([4, 5, 6, 7])

In [50]:
x[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [51]:
x[:, 2]

tensor([ 2,  6, 10])

In [52]:
x[:, 2:4]

tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])

In [53]:
x[:, 2:4] = 100
x

tensor([[  0,   1, 100, 100],
        [  4,   5, 100, 100],
        [  8,   9, 100, 100]])

## 降维与升维

In [ ]:
# 降维: torch.squeeze(input,dim=None,out=None) ,在不指定dim时，张量中所有形状为1的维度都会被删除，例如(A,1,B,1,C)会变成(A,B,C);当给定dim时，只会删除给定的维度(形状必须为1)，例如对于(A,1,B)，squeeze(input,dim=0) 会保持张量不变，只有squeeze(input,dim=1)形状才会变成(A,B)。
a = torch.tensor([1, 2, 3, 4])
print(a, a.shape)

tensor([1, 2, 3, 4]) torch.Size([4])


In [56]:
b = torch.unsqueeze(a, dim = 0)
print(b, b.shape)

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


In [58]:
b = a.unsqueeze(dim = 0)
print(b, b.shape)

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


In [59]:
c = b.squeeze()
print(c, c.shape)

tensor([1, 2, 3, 4]) torch.Size([4])


# 2 加载数据
## Dataset

In [61]:
import os
import pandas as pd
from torchvision.io import read_image
from torch.utils.data import Dataset

class CustomImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

## DataLoaders

In [ ]:
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

# 核心逻辑：下载数据、转化为张量、分包打乱、抽取一包进行验证。这是开始深度学习模型训练之前，确保数据输入正确的标准动作

# datasets.FashionMNIST: 这是一个内置的对象，包含了 60,000 张训练图像和 10,000 张测试图像
training_data = datasets.FashionMNIST(
    root="data",    # 数据存储的路径
    train=True,     # 是否作为训练接
    download=True,  # 如果路径下没数据，自动从网上下载
    transform=ToTensor() # 将图片从PIL格式转换为神经网络能处理的Tensor（张量）：将像素值从[0,255]缩放到[0,1]之间（每个像素值除以255。数值过大会让模型在计算梯度时产生剧烈波动，数值在0到1之间，有利于模型收敛，防止训练崩溃）；将形状从(H, W, C)转换为Pytroch喜欢的(C, H, W)。C是通道数，H是高，W是宽，最终转为(1, 28, 28)
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

# 直接把所有图片塞给模型，显存会爆掉，DataLoader的作用是：把数据切成小块（batch），打乱顺序（shuffle）
train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

train_features, train_labels = next(iter(train_dataloader)) # iter()：把加载器变成一个可迭代的对象，next()：抓取第一个批次的数据
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")

img = train_features[0].squeeze()  # 降维
label = train_labels[0]
print(img.shape)
print(f"Label: {label}")

In [62]:
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform = ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform = ToTensor()
)


100%|██████████| 26.4M/26.4M [03:14<00:00, 136kB/s] 
100%|██████████| 29.5k/29.5k [00:01<00:00, 23.3kB/s]
100%|██████████| 4.42M/4.42M [00:18<00:00, 236kB/s] 
100%|██████████| 5.15k/5.15k [00:00<00:00, 10.1MB/s]


In [63]:
train_dataloader = DataLoader(training_data, batch_size = 64, shuffle = True)
test_dataloader = DataLoader(test_data, batch_size = 64, shuffle = True)

train_features, train_labels = next(iter(train_dataloader))

print(f"train feature batch shape:{train_features.size()}")
print(f"train labels batch shape:{train_labels.size()}")

train feature batch shape:torch.Size([64, 1, 28, 28])
train labels batch shape:torch.Size([64])


In [64]:
img = train_features[0].squeeze()
label = train_labels[0]

print(img.size())
print(f"label:{label}")

torch.Size([28, 28])
label:3


In [65]:
from torch.utils.data import DataLoader
from torch.utils.data import SequentialSampler, RandomSampler
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

train_sampler = RandomSampler(training_data)
test_sampler = SequentialSampler(test_data)

train_dataloader = DataLoader(dataset = training_data, batch_size = 64, sampler = train_sampler)
test_dataloader = DataLoader(dataset = test_data, batch_size = 64, sampler = test_sampler)  

train_features, train_labels = next(iter(train_dataloader))
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")

test_features, test_labels = next(iter(test_dataloader))
print(f"Feature batch shape: {test_features.size()}")
print(f"Labels batch shape: {test_labels.size()}")


Feature batch shape: torch.Size([64, 1, 28, 28])
Labels batch shape: torch.Size([64])
Feature batch shape: torch.Size([64, 1, 28, 28])
Labels batch shape: torch.Size([64])


# 3 训练模型
## 优化模型参数

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f'Using {device} device')

# 这是使用 PyTorch 框架实现的完整深度学习流程，目标是训练一个简单的神经网络来识别 FashionMNIST 数据集（包含 10 类服装图像，如 T 恤、裤子、运动鞋等）

# 1 数据准备
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

learning_rate = 1e-3
batch_size = 64
epochs = 3

train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

# 2 模型结构
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten() # 将28*28的二维图像向量展平成一个784的一维向量
        self.linear_relu_stack = nn.Sequential(  # 顺序容器，按顺序执行
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 10),
            nn.Dropout(p=0.2)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)  # 创建模型实例并移动到指定设备
loss_fn = nn.CrossEntropyLoss()  # 交叉熵损失
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)  # AdamW优化器

# 3 训练循环
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()   # 训练模式，会启用dropout等层
    for batch, (X, y) in enumerate(dataloader, start=1):  # 为dataloader的每个元素自动生成一个计数器，计数器从1开始（而不是从0），返回（计数， 原始元素）。
        # X：(64,1,28,28) Y：(64)
        X, y = X.to(device), y.to(device) # 数据移动到设备
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)
        # Backpropagation
        optimizer.zero_grad()  # 清空旧的梯度
        loss.backward()   # 计算损失函数对每个参数的梯度（导数）
        optimizer.step()  # 根据梯度更新模型权重

        if batch % 100 == 0:  # 每100个批次打印一次
            # loss是一个包含单个值的pytorch张量，.item()将张量值转为python标量
            # len(X)：当前批次的样本数，batch * len(X)到目前为止已处理的样本总数（如果最后一个批次不足64，会有问题）
            loss, current = loss.item(), batch * len(X)
            # >：右对齐；7：总宽度为7个字符；f：浮点数格式；d：十进制整数   
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

# 4 测试循环
def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)  # 测试集大小
    num_batches = len(dataloader)   # 测试集批次大小
    test_loss, correct = 0, 0

    model.eval() # 评估模式：关闭dropout和batchnorm(如果训练有的话。训练时：batchnorm使用当前批次的均值和方差做归一化，同时更新全局统计量，也就是全局的均值和方差；评估模式使用训练时积累的全局均值和方差，不更新统计量，保证测试结果稳定)
    with torch.no_grad():  # 优化操作：测试时不需要计算梯度，可以节省内存和计算资源。一定要记得写这个和model.eval()
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(dim=-1) == y).type(torch.float).sum().item()

    test_loss /= num_batches  # 平均损失
    correct /= size           # 准确率
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)
print("Done!")

Using mps device
Epoch 1
-------------------------------
loss: 0.859291  [ 6400/60000]
loss: 0.781249  [12800/60000]
loss: 0.567190  [19200/60000]
loss: 1.047156  [25600/60000]
loss: 0.336168  [32000/60000]
loss: 0.572114  [38400/60000]
loss: 0.708409  [44800/60000]
loss: 0.707467  [51200/60000]
loss: 0.464506  [57600/60000]
Test Error: 
 Accuracy: 83.9%, Avg loss: 0.445694 

Epoch 2
-------------------------------
loss: 0.503036  [ 6400/60000]
loss: 0.564002  [12800/60000]
loss: 0.504376  [19200/60000]
loss: 0.709904  [25600/60000]
loss: 0.344455  [32000/60000]
loss: 0.486502  [38400/60000]
loss: 0.932251  [44800/60000]
loss: 0.502916  [51200/60000]
loss: 0.485939  [57600/60000]
Test Error: 
 Accuracy: 86.0%, Avg loss: 0.387788 

Epoch 3
-------------------------------
loss: 0.561945  [ 6400/60000]
loss: 0.625954  [12800/60000]
loss: 0.437354  [19200/60000]
loss: 0.782314  [25600/60000]
loss: 0.444722  [32000/60000]
loss: 0.440417  [38400/60000]
loss: 0.758510  [44800/60000]
loss: 0.5

In [69]:
import torch 
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

device = "mps" if torch.backends.mps.is_available else "cpu"
print(f"device is {device}")

training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform = ToTensor()
)

test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform = ToTensor()
)

batch_size = 64
learning_rate = 1e-3
epochs = 3

train_dataloader = DataLoader(dataset = training_data, batch_size = batch_size)
test_dataloader = DataLoader(dataset = test_data, batch_size = batch_size)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.liner_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 10),
            nn.Dropout(p = 0.2)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.liner_relu_stack(x)
        return logits 
    
model = NeuralNetwork().to(device)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)

def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)

    model.train()

    for batch_id, (X,y) in enumerate(dataloader, start = 1):
        X, y = X.to(device), y.to(device)
        pred = model(X)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch_id % 100 == 0:
            loss, current = loss.item(), batch_id * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d} / {size:>5d}]")


def test_loop(dataloader: DataLoader, model, loss_fn):
    size = len(dataloader.dataset)
    batch_num = len(dataloader)
    test_loss, correct = 0, 0

    model.eval()

    with torch.no_grad():
        for X,y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()  #记得.item()
            correct += (pred.argmax(dim = -1) == y).type(torch.float).sum().item()

    test_loss /= batch_num
    correct /= size

    print(f"test: \n accuracy:{(100 * correct):>0.1f}%, avg loss: {test_loss:>8f} \n")

for epoch in range(epochs):
    print(f"Epoch:{epoch+1}\n -----------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)

print("Done")


device is mps
Epoch:1
 -----------------
loss: 0.918749  [ 6400 / 60000]
loss: 0.784420  [12800 / 60000]
loss: 0.539821  [19200 / 60000]
loss: 0.975703  [25600 / 60000]
loss: 0.547446  [32000 / 60000]
loss: 0.530928  [38400 / 60000]
loss: 0.878320  [44800 / 60000]
loss: 0.615322  [51200 / 60000]
loss: 0.632237  [57600 / 60000]
test: 
 accuracy:83.9%, avg loss: 0.437577 

Epoch:2
 -----------------
loss: 0.609730  [ 6400 / 60000]
loss: 0.665684  [12800 / 60000]
loss: 0.520877  [19200 / 60000]
loss: 0.813563  [25600 / 60000]
loss: 0.536641  [32000 / 60000]
loss: 0.591464  [38400 / 60000]
loss: 0.928756  [44800 / 60000]
loss: 0.559336  [51200 / 60000]
loss: 0.412994  [57600 / 60000]
test: 
 accuracy:85.4%, avg loss: 0.409152 

Epoch:3
 -----------------
loss: 0.655895  [ 6400 / 60000]
loss: 0.607176  [12800 / 60000]
loss: 0.441106  [19200 / 60000]
loss: 0.749057  [25600 / 60000]
loss: 0.293225  [32000 / 60000]
loss: 0.548186  [38400 / 60000]
loss: 0.742879  [44800 / 60000]
loss: 0.456964 

# 4 保存及加载模型
## 保存和加载模型权重

In [70]:
import torch
import torchvision.models as models

model = models.vgg16(pretrained = True)
torch.save(model.state_dict(), "model_weight.pth")  # pytorch模型会把所有参数存储在状态字典中

/opt/homebrew/Caskroom/miniconda/base/envs/transformers_learn/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/opt/homebrew/Caskroom/miniconda/base/envs/transformers_learn/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /Users/wangmeiling/.cache/torch/hub/checkpoints/vgg16-397923af.pth


  8%|▊         | 43.0M/528M [00:12<02:21, 3.60MB/s]


KeyboardInterrupt: 

In [71]:
model = models.vgg16()
model.load_state_dict(torch.load("model_weight.pth"))
model.eval()

FileNotFoundError: [Errno 2] No such file or directory: 'model_weight.pth'

## 保存和加载完整模型

In [72]:
# 存储模型权重的方式可以节省空间，但是加载前需要构建一个结构完全相同的模型实例来承接权重
# 如果希望存储模型权重的同时，也一起保存模型结构，就需要将整个模型传给torch.save()

import torch
import torchvision.models as models

model = models.vgg16(pretrined = True)

torch.save(model, "model.pth")

TypeError: VGG.__init__() got an unexpected keyword argument 'pretrined'

In [73]:
model = torch.load("model.pth")

FileNotFoundError: [Errno 2] No such file or directory: 'model.pth'